sudo: required
services: 
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project app-in-k8s
  - gcloud config set compute/zone europe-central2-a
  - gcloud container clusters get-credentials app-in-k8s
  - docker login -u "$DOCKER_USERNAME" -p  "$DOCKER_PASSWORD"
  - docker build -t mroobert/react-test -f ./client/Dockerfile.dev ./client
script: 
  - docker run -e CI=true mroobert/react-test npm test
 
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
